#include "crypto.h"

/*
 * Function: rand_bytes
 * --------------------
 * Generates a random byte array of the specified length.
 *
 * length: The length of the random byte array to generate.
 *
 * returns: A pointer to the generated byte array, or NULL on failure.
 */
unsigned char *rand_bytes(int length)
{
    unsigned char *buffer = (unsigned char *)mp_alloc(mpool_, length);
    if (!buffer)
        return NULL;

    if (RAND_bytes(buffer, length) != 1)
    {
        mp_free(mpool_, buffer);
        return NULL;
    }

    return buffer;
}

/*
 * Function: sha1
 * --------------
 * Computes the SHA-1 hash of the given data.
 *
 * data: The input data to hash.
 *
 * returns: A pointer to the computed SHA-1 hash, or NULL on failure.
 */
unsigned char *sha1(const unsigned char *data, size_t len)
{
    unsigned char *hash = mp_alloc(mpool_, SHA_DIGEST_LENGTH);
    if (!hash)
        return NULL;

    if (!SHA1(data, len, hash))
    {
        mp_free(mpool_, hash);
        return NULL;
    }

    return hash;
}

/*
 * Function: sha256
 * ---------------
 * Computes the SHA-256 hash of the given data.
 *
 * data: The input data to hash.
 *
 * returns: A pointer to the computed SHA-256 hash, or NULL on failure.
 */
unsigned char *sha256(const unsigned char *data, size_t len)
{
    unsigned char *hash = mp_alloc(mpool_, SHA256_DIGEST_LENGTH);
    if (!hash)
        return NULL;

    if (!SHA256(data, len, hash))
    {
        mp_free(mpool_, hash);
        return NULL;
    }

    return hash;
}

/*
 * Function: sha512
 * ---------------
 * Computes the SHA-512 hash of the given data.
 *
 * data: The input data to hash.
 *
 * returns: A pointer to the computed SHA-512 hash, or NULL on failure.
 */

unsigned char *sha512(const unsigned char *data, size_t len)
{
    unsigned char *hash = mp_alloc(mpool_, SHA512_DIGEST_LENGTH);
    if (!hash)
        return NULL;

    if (!SHA512(data, len, hash))
    {
        mp_free(mpool_, hash);
        return NULL;
    }

    return hash;
}

/*
 * Function: aes_encrypt
 * ----------------------
 * Encrypts the given data using AES encryption.
 *
 * data: The input data to encrypt.
 * key: The AES key structure containing the key and IV.
 * key_size: The size of the AES key (128, 192, or 256 bits).
 *
 * returns: A pointer to the encrypted data, or NULL on failure.
 */
unsigned char *aes_encrypt(const unsigned char *data, size_t len, AESkey_t key, int key_size, int *out_len)
{
    const EVP_CIPHER *cipher = NULL;
    switch (key_size)
    {
    case 128:
        cipher = EVP_aes_128_cbc();
        break;
    case 192:
        cipher = EVP_aes_192_cbc();
        break;
    case 256:
        cipher = EVP_aes_256_cbc();
        break;
    default:
        return NULL;
    }

    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    if (!ctx)
        return NULL;

    unsigned char *out = malloc(len + AES_BLOCK_SIZE); // Padded output
    if (!out)
    {
        EVP_CIPHER_CTX_free(ctx);
        return NULL;
    }

    int len1 = 0, len2 = 0;

    EVP_EncryptInit_ex(ctx, cipher, NULL, key.key, key.iv);
    EVP_CIPHER_CTX_set_padding(ctx, 1);

    if (!EVP_EncryptUpdate(ctx, out, &len1, data, (int)len) ||
        !EVP_EncryptFinal_ex(ctx, out + len1, &len2))
    {
        EVP_CIPHER_CTX_free(ctx);
        free(out);
        return NULL;
    }

    *out_len = len1 + len2;
    EVP_CIPHER_CTX_free(ctx);
    return out;
}

/*
 * Function: aes_decrypt
 * ----------------------
 * Decrypts the given data using AES decryption.
 *
 * data: The input data to decrypt.
 * key: The AES key structure containing the key and IV.
 * key_size: The size of the AES key (128, 192, or 256 bits).
 *
 * returns: A pointer to the decrypted data, or NULL on failure.
 */

unsigned char *aes_decrypt(const unsigned char *data, size_t len, AESkey_t key, int key_size, int *out_len)
{
    const EVP_CIPHER *cipher = NULL;
    switch (key_size)
    {
    case 128:
        cipher = EVP_aes_128_cbc();
        break;
    case 192:
        cipher = EVP_aes_192_cbc();
        break;
    case 256:
        cipher = EVP_aes_256_cbc();
        break;
    default:
        return NULL;
    }

    EVP_CIPHER_CTX *ctx = EVP_CIPHER_CTX_new();
    if (!ctx)
        return NULL;

    unsigned char *out = malloc(len);
    if (!out)
    {
        EVP_CIPHER_CTX_free(ctx);
        return NULL;
    }

    int len1 = 0, len2 = 0;

    EVP_DecryptInit_ex(ctx, cipher, NULL, key.key, key.iv);
    EVP_CIPHER_CTX_set_padding(ctx, 1);

    if (!EVP_DecryptUpdate(ctx, out, &len1, data, (int)len) ||
        !EVP_DecryptFinal_ex(ctx, out + len1, &len2))
    {
        EVP_CIPHER_CTX_free(ctx);
        free(out);
        return NULL;
    }

    *out_len = len1 + len2;
    EVP_CIPHER_CTX_free(ctx);
    return out;
}

/*
 * Function: aes128_enc
 * ---------------------
 * Encrypts the given data using AES-128 encryption.
 *
 * data: The input data to encrypt.
 * key: The AES key structure containing the key and IV.
 *
 * returns: A pointer to the encrypted data, or NULL on failure.
 */
unsigned char *aes128_enc(const unsigned char *data, size_t len, AESkey_t key)
{
    int out_len;
    return aes_encrypt(data, len, key, 128, &out_len);
}

/*
 * Function: aes192_enc
 * ---------------------
 * Encrypts the given data using AES-192 encryption.
 *
 * data: The input data to encrypt.
 * key: The AES key structure containing the key and IV.
 *
 * returns: A pointer to the encrypted data, or NULL on failure.
 */
unsigned char *aes192_enc(const unsigned char *data, size_t len, AESkey_t key)
{
    int out_len;
    return aes_encrypt(data, len, key, 192, &out_len);
}

/*
 * Function: aes256_enc
 * ---------------------
 * Encrypts the given data using AES-256 encryption.
 *
 * data: The input data to encrypt.
 * key: The AES key structure containing the key and IV.
 *
 * returns: A pointer to the encrypted data, or NULL on failure.
 */
unsigned char *aes256_enc(const unsigned char *data, size_t len, AESkey_t key)
{
    int out_len;
    return aes_encrypt(data, len, key, 256, &out_len);
}

/*
 * Function: aes128_dec
 * ---------------------
 * Decrypts the given data using AES-128 decryption.
 *
 * data: The input data to decrypt.
 * key: The AES key structure containing the key and IV.
 *
 * returns: A pointer to the decrypted data, or NULL on failure.
 */
unsigned char *aes128_dec(const unsigned char *data, size_t len, AESkey_t key)
{
    int out_len;
    return aes_decrypt(data, len, key, 128, &out_len);
}

/*
 * Function: aes192_dec
 * ---------------------
 * Decrypts the given data using AES-192 decryption.
 *
 * data: The input data to decrypt.
 * key: The AES key structure containing the key and IV.
 *
 * returns: A pointer to the decrypted data, or NULL on failure.
 */
unsigned char *aes192_dec(const unsigned char *data, size_t len, AESkey_t key)
{
    int out_len;
    return aes_decrypt(data, len, key, 192, &out_len);
}

/*
 * Function: aes256_dec
 * ---------------------
 * Decrypts the given data using AES-256 decryption.
 *
 * data: The input data to decrypt.
 * key: The AES key structure containing the key and IV.
 *
 * returns: A pointer to the decrypted data, or NULL on failure.
 */
unsigned char *aes256_dec(const unsigned char *data, size_t len, AESkey_t key)
{
    int out_len;
    return aes_decrypt(data, len, key, 256, &out_len);
}